const express = require('express')
const router = express.Router()
const { postimages, getproperties, updateproperties, deleteroperties, getsingleproperties } = require('../Controller/propertycontrol')
const {storage} = require('../utlis/cloudinary')
const multer = require('multer')
const { verifyTokenAndAuthorization, verifytoken } = require('../middleware/verifytoken')
const upload = multer({storage})
router.post('/post/',upload.array('images',6),verifytoken,postimages)
router.put("/updateproperty/:id",upload.array('images',6),verifyTokenAndAuthorization,updateproperties)
router.get('/getproperty',getproperties)
router.get('/getsingleproperty/:id',getsingleproperties)
router.delete('/deleteproperty/:id',verifyTokenAndAuthorization,deleteroperties)
module.exports = router;
