const express = require("express")
const router = express.Router()
const { userregisters, postEmailConfirmation, signIn,signout, userlist, singleuser, resendverificationemail } = require("../Controller/usercontrol")
const {storage} = require('../utlis/cloudinary')
const multer = require('multer')
const upload = multer({storage})
const { registerationvalidation } = require("../validation")
router.post("/register",upload.array("images"),registerationvalidation,userregisters)
// router.post('/confirmation/:token',postEmailConfirmation)
router.post('/signin',signIn)
router.post('/signout',signout)
router.get('/user',userlist)
router.get('/user/:id',singleuser)
// router.post('/resendlink',resendverificationemail)
module.exports = router