const express = require("express")
const router = express.Router()
const { userregisters, signIn,signout, userlist, singleuser, deleteuser, updateuser } = require("../Controller/usercontrol")
const {storage} = require('../utlis/cloudinary')
const multer = require('multer')
const upload = multer({storage})
const { registerationvalidation } = require("../validation")
const { verifyTokenAndAuthorization } = require("../middleware/verifytoken")
const { deleteroperties } = require("../Controller/propertycontrol")
router.post("/register",upload.array("images"),registerationvalidation,userregisters)
router.post('/signin',signIn)
router.post('/signout',signout)
router.get('/user',userlist)
router.get('/user/:id',singleuser)
router.put('/updateuser/:id',upload.array('images'),verifyTokenAndAuthorization,updateuser)
router.delete('/deleteuser/:id',verifyTokenAndAuthorization,deleteuser)
module.exports = router